export const WORKOUT_PLAN = {
  monday: {
    name: 'Piernas',
    emoji: '🦵',
    day: 'Lunes',
    color: '#22C55E',
    gradient: ['#22C55E', '#16A34A'],
    tip: 'Mantén la espalda recta en todos los ejercicios de piernas.',
    exercises: [
      {
        id: 'leg1',
        name: 'Sentadilla Goblet',
        sets: 4,
        reps: '12-15',
        rest: 90,
        muscleGroup: 'Cuádriceps',
        equipment: 'Mancuerna',
        youtubeId: 'MxsFDhcyFyE',
        technique: 'Sostén la mancuerna a la altura del pecho con ambas manos. Pies al ancho de hombros, punteras hacia afuera 30°. Desciende manteniendo el torso erguido hasta que los muslos queden paralelos al suelo. Empuja con los talones al subir.',
        warning: false,
        warningText: '',
      },
      {
        id: 'leg2',
        name: 'Prensa de Piernas',
        sets: 4,
        reps: '15-20',
        rest: 90,
        muscleGroup: 'Cuádriceps / Glúteos',
        equipment: 'Máquina',
        youtubeId: 'IZxyjW7MPJQ',
        technique: 'Coloca los pies en el centro de la plataforma al ancho de hombros. Baja controlado hasta 90° en rodillas. No bloquees las rodillas al extender. Empuja con el talón y la planta completa.',
        warning: false,
        warningText: '',
      },
      {
        id: 'leg3',
        name: 'Extensión de Cuádriceps',
        sets: 3,
        reps: '15-20',
        rest: 60,
        muscleGroup: 'Cuádriceps',
        equipment: 'Máquina',
        youtubeId: 'YyvSfVjQeL0',
        technique: 'Ajusta el asiento para que la rodilla esté alineada con el pivote. Extiende completamente y baja de forma controlada en 3 segundos. Evita usar impulso.',
        warning: false,
        warningText: '',
      },
      {
        id: 'leg4',
        name: 'Curl Femoral Tumbado',
        sets: 3,
        reps: '12-15',
        rest: 60,
        muscleGroup: 'Isquiotibiales',
        equipment: 'Máquina',
        youtubeId: 'n0BaD9-GESA',
        technique: 'Ajusta los rodillos para que queden sobre los talones. Flexiona controlado y aprieta isquios al máximo. Baja en 3 segundos sin soltar de golpe.',
        warning: false,
        warningText: '',
      },
      {
        id: 'leg5',
        name: 'Elevación de Talones (Gemelos)',
        sets: 4,
        reps: '20-25',
        rest: 45,
        muscleGroup: 'Gemelos',
        equipment: 'Máquina / Libre',
        youtubeId: '9AjrZlqga3Q',
        technique: 'Coloca las puntas en el escalón, talones libres. Sube lo máximo posible y aguanta 1 segundo arriba. Baja hasta estirar bien el gemelo. Movimiento lento y controlado.',
        warning: false,
        warningText: '',
      },
      {
        id: 'leg6',
        name: 'Hip Thrust con Barra',
        sets: 4,
        reps: '12-15',
        rest: 90,
        muscleGroup: 'Glúteos',
        equipment: 'Barra / Banco',
        youtubeId: 'LM8XHLYJoYs',
        technique: 'Apoya la espalda alta en el banco, barra sobre caderas con acolchado. Pies al ancho de hombros. Sube empujando con glúteos hasta alinear caderas con rodillas. Aprieta glúteos 1 seg arriba.',
        warning: false,
        warningText: '',
      },
    ],
  },
  tuesday: {
    name: 'Cardio + Core',
    emoji: '🏃',
    day: 'Martes',
    color: '#3B82F6',
    gradient: ['#3B82F6', '#2563EB'],
    tip: 'Mantén el core activo durante todo el cardio. Hidratación clave hoy.',
    exercises: [
      {
        id: 'cardio1',
        name: 'Caminata en Inclinación',
        sets: 1,
        reps: '30-40 min',
        rest: 0,
        muscleGroup: 'Cardio',
        equipment: 'Cinta',
        youtubeId: 'PjIFTisYLZI',
        technique: 'Inclinación 10-12%, velocidad 5-6 km/h. No te agarres de los laterales. Mantén postura erguida. Ideal para quemar grasa sin impacto en la columna.',
        warning: false,
        warningText: '',
      },
      {
        id: 'core1',
        name: 'Plancha Isométrica',
        sets: 4,
        reps: '30-45 seg',
        rest: 45,
        muscleGroup: 'Core',
        equipment: 'Esterilla',
        youtubeId: 'pvIjxtSB_0s',
        technique: 'Apoya antebrazos y puntas de pies. Cuerpo recto como tabla. Aprieta glúteos, core y no dejes caer las caderas. Respira normal durante el ejercicio.',
        warning: false,
        warningText: '',
      },
      {
        id: 'core2',
        name: 'Crunch Abdominal',
        sets: 3,
        reps: '20-25',
        rest: 45,
        muscleGroup: 'Abdomen',
        equipment: 'Esterilla',
        youtubeId: 'Xyd_fa5zoEU',
        technique: 'Tumbado, rodillas flexionadas. Manos detrás de la cabeza sin jalar el cuello. Sube contrayendo el abdomen, no el cuello. Exhala al subir, inhala al bajar.',
        warning: false,
        warningText: '',
      },
      {
        id: 'core3',
        name: 'Elevación de Piernas Tumbado',
        sets: 3,
        reps: '15-20',
        rest: 45,
        muscleGroup: 'Abdomen inferior',
        equipment: 'Esterilla',
        youtubeId: 'JB2oyawG9KI',
        technique: 'Tumbado boca arriba, manos bajo los glúteos. Sube las piernas rectas a 90° y baja controlado sin tocar el suelo. No arquees la espalda lumbar.',
        warning: true,
        warningText: '⚠️ L4L5: Baja piernas solo hasta donde no haya tensión lumbar. Si hay molestia, reduce el rango.',
      },
      {
        id: 'core4',
        name: 'Bird Dog',
        sets: 3,
        reps: '12 cada lado',
        rest: 45,
        muscleGroup: 'Core / Lumbar',
        equipment: 'Esterilla',
        youtubeId: 'wiFNA3sqjCA',
        technique: 'A cuatro patas, extiende brazo derecho y pierna izquierda simultáneamente. Mantén la espalda horizontal, sin rotar la cadera. Aguanta 2 seg y alterna. Excelente para L4L5.',
        warning: false,
        warningText: '',
      },
      {
        id: 'core5',
        name: 'Dead Bug',
        sets: 3,
        reps: '10 cada lado',
        rest: 45,
        muscleGroup: 'Core / Estabilizadores',
        equipment: 'Esterilla',
        youtubeId: 'g_7lZMqHRaU',
        technique: 'Tumbado, brazos al techo, rodillas a 90°. Baja brazo derecho y pierna izquierda opuesta sin que la zona lumbar se separe del suelo. Vuelve al centro y alterna.',
        warning: false,
        warningText: '',
      },
    ],
  },
  wednesday: {
    name: 'Empuje',
    emoji: '💪',
    day: 'Miércoles',
    color: '#F97316',
    gradient: ['#F97316', '#EA580C'],
    tip: 'Agarre neutro cuando sea posible para proteger los tendones del bíceps.',
    exercises: [
      {
        id: 'push1',
        name: 'Press Banca Agarre Neutro',
        sets: 4,
        reps: '10-12',
        rest: 90,
        muscleGroup: 'Pecho',
        equipment: 'Mancuernas',
        youtubeId: 'o0MsNXgcKHc',
        technique: 'Tumbado en banco plano, mancuernas con agarre neutro (palmas enfrentadas). Baja controlado hasta pecho y empuja hacia arriba. El agarre neutro reduce estrés en tendones del bíceps.',
        warning: false,
        warningText: '',
      },
      {
        id: 'push2',
        name: 'Press Inclinado con Mancuernas',
        sets: 4,
        reps: '10-12',
        rest: 90,
        muscleGroup: 'Pecho Superior',
        equipment: 'Mancuernas / Banco inclinado',
        youtubeId: 'DbFgADa2PL8',
        technique: 'Banco a 30-45°. Mancuernas a la altura del pecho. Empuja hacia arriba y ligeramente hacia el centro. Baja controlado. Mantén escápulas retraídas.',
        warning: false,
        warningText: '',
      },
      {
        id: 'push3',
        name: 'Aperturas con Mancuernas',
        sets: 3,
        reps: '12-15',
        rest: 60,
        muscleGroup: 'Pecho',
        equipment: 'Mancuernas / Banco',
        youtubeId: 'eozdVDA78K0',
        technique: 'Banco plano, mancuernas arriba con codos ligeramente flexionados. Abre los brazos en arco hasta que sientas el pecho estirado. Vuelve apretando el pecho. No bajes demasiado.',
        warning: false,
        warningText: '',
      },
      {
        id: 'push4',
        name: 'Press Militar con Mancuernas',
        sets: 4,
        reps: '10-12',
        rest: 90,
        muscleGroup: 'Hombros',
        equipment: 'Mancuernas',
        youtubeId: 'qEwKCR5JCog',
        technique: 'Sentado o de pie, mancuernas a la altura de los hombros. Empuja hacia arriba sin arquear la lumbar. Baja controlado. No uses impulso de piernas.',
        warning: true,
        warningText: '⚠️ L4L5: Realiza sentado con respaldo para proteger la columna lumbar.',
      },
      {
        id: 'push5',
        name: 'Elevaciones Laterales',
        sets: 4,
        reps: '15-20',
        rest: 60,
        muscleGroup: 'Deltoides lateral',
        equipment: 'Mancuernas',
        youtubeId: '3VcKaXpzqRo',
        technique: 'De pie, mancuernas a los lados. Sube los brazos lateralmente hasta la altura de los hombros con el codo ligeramente flexionado. Baja controlado en 3 segundos. Evita el balanceo.',
        warning: false,
        warningText: '',
      },
      {
        id: 'push6',
        name: 'Fondos en Máquina (Tríceps)',
        sets: 3,
        reps: '12-15',
        rest: 60,
        muscleGroup: 'Tríceps',
        equipment: 'Máquina',
        youtubeId: 'tcZNEstjqVA',
        technique: 'Ajusta el asiento para que los codos queden al lado del cuerpo. Empuja hacia abajo extendiendo completamente los codos. Vuelve controlado sin soltar la tensión.',
        warning: false,
        warningText: '',
      },
    ],
  },
  thursday: {
    name: 'Tracción',
    emoji: '🏋️',
    day: 'Jueves',
    color: '#A855F7',
    gradient: ['#A855F7', '#7C3AED'],
    tip: '⚠️ Bíceps: Agarre neutro siempre. Evita supinación forzada.',
    exercises: [
      {
        id: 'pull1',
        name: 'Jalón al Pecho Agarre Neutro',
        sets: 4,
        reps: '10-12',
        rest: 90,
        muscleGroup: 'Dorsal',
        equipment: 'Polea / Barra V',
        youtubeId: 'CAwf7n6Luuc',
        technique: 'Usa la barra en V o triángulo para agarre neutro. Siéntate, pies en el suelo. Jala hacia el pecho manteniendo pecho erguido. El agarre neutro PROTEGE los tendones del bíceps.',
        warning: true,
        warningText: '⚠️ Tendones bíceps: OBLIGATORIO agarre neutro. No uses barra recta con supinación.',
      },
      {
        id: 'pull2',
        name: 'Remo con Mancuerna',
        sets: 4,
        reps: '10-12 cada lado',
        rest: 75,
        muscleGroup: 'Dorsal / Romboides',
        equipment: 'Mancuerna / Banco',
        youtubeId: 'pYcpY20QaE8',
        technique: 'Apoya rodilla y mano en el banco. Espalda horizontal. Jala la mancuerna hacia la cadera, no hacia el hombro. El agarre neutro es natural aquí. Aprieta el dorsal en lo alto.',
        warning: false,
        warningText: '',
      },
      {
        id: 'pull3',
        name: 'Remo en Máquina',
        sets: 3,
        reps: '12-15',
        rest: 75,
        muscleGroup: 'Dorsal / Romboides',
        equipment: 'Máquina',
        youtubeId: 'GZbfZ033f74',
        technique: 'Pecho contra el apoyo, agarre neutro cuando sea posible. Jala los codos hacia atrás apretando los romboides. Mantén el pecho contra el apoyo durante todo el movimiento.',
        warning: true,
        warningText: '⚠️ Tendones bíceps: Prefiere agarre neutro o pronado. Evita supinación máxima.',
      },
      {
        id: 'pull4',
        name: 'Face Pull con Cuerda',
        sets: 4,
        reps: '15-20',
        rest: 60,
        muscleGroup: 'Deltoides posterior / Rotadores',
        equipment: 'Polea alta',
        youtubeId: 'rep-qVOkqgk',
        technique: 'Polea a la altura de los ojos. Jala la cuerda hacia tu cara, separando los extremos. Codos al nivel de los hombros o más arriba. Excelente para salud de hombros.',
        warning: false,
        warningText: '',
      },
      {
        id: 'pull5',
        name: 'Encogimiento de Hombros',
        sets: 3,
        reps: '15-20',
        rest: 60,
        muscleGroup: 'Trapecios',
        equipment: 'Mancuernas',
        youtubeId: 'cJRVVxmytaM',
        technique: 'De pie con mancuernas a los lados, agarre neutro. Sube los hombros hacia las orejas y aguanta 1 segundo. Baja lento. No rotar los hombros, solo subir y bajar.',
        warning: true,
        warningText: '⚠️ Tendones bíceps: Agarre neutro obligatorio. No uses barra.',
      },
    ],
  },
  friday: {
    name: 'Full Body',
    emoji: '⚡',
    day: 'Viernes',
    color: '#EAB308',
    gradient: ['#EAB308', '#CA8A04'],
    tip: 'Día de integración total. Pesos moderados, técnica perfecta.',
    exercises: [
      {
        id: 'fb1',
        name: 'Peso Muerto Rumano',
        sets: 4,
        reps: '10-12',
        rest: 90,
        muscleGroup: 'Isquiotibiales / Glúteos / Lumbar',
        equipment: 'Barra o Mancuernas',
        youtubeId: 'JCXUYuzwNrM',
        technique: 'Pies al ancho de caderas, rodillas ligeramente flexionadas. Baja la barra deslizando por las piernas, empujando caderas hacia atrás. Espalda RECTA siempre. Para L4L5: no bajes más allá de la tibia.',
        warning: true,
        warningText: '⚠️ L4L5: Mantén espalda NEUTRAL siempre. No redondees la lumbar. Si hay dolor, detente.',
      },
      {
        id: 'fb2',
        name: 'Press de Banca con Mancuernas',
        sets: 3,
        reps: '10-12',
        rest: 90,
        muscleGroup: 'Pecho',
        equipment: 'Mancuernas',
        youtubeId: 'o0MsNXgcKHc',
        technique: 'Banco plano, agarre neutro. Baja mancuernas hasta el nivel del pecho con codos a 45°. Empuja hacia arriba. Mantén pies en el suelo y espalda neutra.',
        warning: false,
        warningText: '',
      },
      {
        id: 'fb3',
        name: 'Jalón Neutro al Pecho',
        sets: 3,
        reps: '10-12',
        rest: 90,
        muscleGroup: 'Dorsal',
        equipment: 'Polea / Barra V',
        youtubeId: 'CAwf7n6Luuc',
        technique: 'Barra V o triángulo. Jala hacia el pecho con codos hacia abajo. Contrae el dorsal en lo alto del movimiento. Agarre neutro protege los bíceps.',
        warning: true,
        warningText: '⚠️ Tendones bíceps: Agarre neutro siempre en este ejercicio.',
      },
      {
        id: 'fb4',
        name: 'Press de Hombro Sentado',
        sets: 3,
        reps: '10-12',
        rest: 75,
        muscleGroup: 'Deltoides',
        equipment: 'Mancuernas',
        youtubeId: 'qEwKCR5JCog',
        technique: 'Sentado con respaldo. Mancuernas a la altura de los hombros, agarre neutro o semipronado. Empuja hacia arriba sin arruinar la postura lumbar.',
        warning: true,
        warningText: '⚠️ L4L5: Siempre sentado con respaldo. No de pie.',
      },
      {
        id: 'fb5',
        name: 'Elevaciones Laterales con Cable',
        sets: 3,
        reps: '15-20',
        rest: 45,
        muscleGroup: 'Deltoides lateral',
        equipment: 'Cable',
        youtubeId: 'PPrmboSVPTY',
        technique: 'Cable por debajo. Eleva el brazo lateralmente hasta hombros con codo ligeramente flexionado. El cable da tensión constante. Baja muy controlado.',
        warning: false,
        warningText: '',
      },
      {
        id: 'fb6',
        name: 'Plancha con Elevación de Brazo',
        sets: 3,
        reps: '10 cada lado',
        rest: 45,
        muscleGroup: 'Core / Estabilizadores',
        equipment: 'Esterilla',
        youtubeId: 'wiFNA3sqjCA',
        technique: 'Posición de plancha en manos. Eleva un brazo al frente manteniendo el cuerpo estable. No rotar la cadera. Alterna lados.',
        warning: false,
        warningText: '',
      },
    ],
  },
};

export const DAYS_ORDER = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'];

export const DAY_TO_INDEX = {
  0: null,      // Domingo - descanso
  1: 'monday',
  2: 'tuesday',
  3: 'wednesday',
  4: 'thursday',
  5: 'friday',
  6: null,      // Sábado - descanso
};

export const MOTIVATIONAL_QUOTES = [
  { text: 'El dolor que sientes hoy será la fuerza que sentirás mañana.', author: 'Desconocido' },
  { text: 'No se trata de ser el mejor. Se trata de ser mejor que ayer.', author: 'Desconocido' },
  { text: 'Tu cuerpo puede soportarlo. Es tu mente la que debes convencer.', author: 'Desconocido' },
  { text: 'El único mal entrenamiento es el que no hiciste.', author: 'Desconocido' },
  { text: 'Trabaja en silencio. Deja que tu progreso haga el ruido.', author: 'Desconocido' },
  { text: 'Cada repetición es un ladrillo en el edificio de tu mejor versión.', author: 'Desconocido' },
  { text: 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', author: 'R. Collier' },
];
